version: '3.8'

services:
  smtp:
    image: rnwood/smtp4dev:latest
    ports:
      - "5001:80"       # Changed host port to 5001
      - "2526:25"       # Changed host port to 2526
  db:
    image: postgres
    ports:
      - 5433:5432       # Changed host port to 5433
    volumes:
      - './postgres_data:/var/lib/postgresql/data'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elevar
      PGDATA: /var/lib/postgresql/data/pgdata

  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - './mongodb_data:/data/db'
      - './mongodb_init:/docker-entrypoint-initdb.d'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

  verdaccio:
    image: verdaccio/verdaccio:latest
    ports:
      - "4873:4873"
    volumes:
      - './verdaccio/storage:/verdaccio/storage'
      - './verdaccio/conf:/verdaccio/conf'
    environment:
      - VERDACCIO_AUTH_JWT_SECRET=your_jwt_secret

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001" # Console port
    volumes:
      - './minio_data:/data'
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"